CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    hostname VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(120) NOT NULL,
    vendor VARCHAR(80) NOT NULL,
    device_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE monitoring_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES devices(id),
    name VARCHAR(100) NOT NULL,
    target_type VARCHAR(24) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER,
    oid VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    interval_seconds INTEGER NOT NULL DEFAULT 60,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_target_device_name UNIQUE (device_id, name)
);

CREATE TABLE monitoring_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT NOT NULL REFERENCES monitoring_targets(id),
    name VARCHAR(120) NOT NULL,
    metric_name VARCHAR(120) NOT NULL,
    warning_threshold DOUBLE PRECISION,
    critical_threshold DOUBLE PRECISION,
    suppression_seconds INTEGER NOT NULL DEFAULT 300,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE monitoring_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT REFERENCES devices(id),
    target_id BIGINT REFERENCES monitoring_targets(id),
    source VARCHAR(24) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    event_key VARCHAR(180) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    raw_message TEXT,
    facility VARCHAR(80),
    protocol VARCHAR(40),
    metric_value DOUBLE PRECISION,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duplicate BOOLEAN NOT NULL DEFAULT FALSE,
    fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES devices(id),
    rule_id BIGINT REFERENCES monitoring_rules(id),
    alert_key VARCHAR(180) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    first_occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_count INTEGER NOT NULL,
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE alert_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id),
    from_status VARCHAR(24),
    to_status VARCHAR(24) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notification_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    channel VARCHAR(40) NOT NULL,
    address VARCHAR(255) NOT NULL,
    minimum_severity VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id),
    idempotency_key VARCHAR(180) NOT NULL UNIQUE,
    channel VARCHAR(40) NOT NULL,
    status VARCHAR(24) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tcp_ping_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT REFERENCES devices(id),
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    success BOOLEAN NOT NULL,
    response_millis BIGINT NOT NULL,
    error_type VARCHAR(80),
    error_message VARCHAR(500),
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    retry_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id VARCHAR(80),
    detail VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    role VARCHAR(40) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_event_occurred_at ON monitoring_events (occurred_at DESC);
CREATE INDEX idx_event_source_time ON monitoring_events (source, occurred_at DESC);
CREATE INDEX idx_event_fingerprint_time ON monitoring_events (fingerprint, occurred_at DESC);
CREATE INDEX idx_alert_active_key ON alerts (device_id, alert_key, status, last_occurred_at DESC);
CREATE INDEX idx_alert_status_time ON alerts (status, last_occurred_at DESC);
CREATE INDEX idx_tcp_ping_checked_at ON tcp_ping_results (checked_at DESC);
CREATE INDEX idx_audit_created_at ON audit_logs (created_at DESC);

